# https://github.com/release-it/release-it/blob/master/config/release-it.json
git:
  commitMessage: 'chore: release v${version}'
github:
  release: true
  releaseName: 'v${version}'
hooks:
  before:init: yarn test
plugins:
  '@release-it/conventional-changelog': # https://github.com/release-it/conventional-changelog
    preset: angular
